[package]
name = "sloth-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
tempfile = "3"